title: "Application Onboarding (Open)"
path: /applications-onboard/
order: 5
section:
  #- title: Onboarding Applications to an IntelÂ® Smart Edge Open Single-Node Cluster
  - title: Onboarding Applications (Open)
    path: {{site.main_url}}/docs/application-onboarding/application-onboarding-cmdline
    meta_title: 
    meta_description: 
